#!/bin/bash
# Backup MMDVM logs during shutdown/reboots
#
#rpi-rw
xro=$(grep "/dev/root" /proc/mounts | sed -n "s/.*\(r[ow]\).*/\1/p")
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,rw / ; sudo mount -o remount,rw /boot
fi
#
rbt=0
while getopts ur opt; do
  case $opt in
    r) rbt=1;;
  esac
done
shift $(($OPTIND - 1))
#
if [ ! -d /home/pi-star/.mlogs ]; then
  sudo mkdir /home/pi-star/.mlogs
fi
#
sudo cp -p /var/log/pi-star/MMDVM* /home/pi-star/.mlogs
#
#logger -t "[$$]" "Pi-Star --> MMDVM logs backed up"
#
if [ $rbt == 1 ]; then
  sudo touch /home/pi-star/.mlogs/reboot-$(date +%Y-%m-%d-%H:%M:%S)
fi
#
#rpi-ro
if [ "$xro" == "ro" ]; then
  sudo mount -o remount,ro / ; sudo mount -o remount,ro /boot
fi
